fix: export data format arrow/feather
ieeh-tu-dresden/powerfactory-tools pull request #245
Opened 2024-07-10 13:46 UTC by SebastianDD

Fixes #244

2024-07-25 12:40 UTC, SebastianDD commented
may also need to adjust the control example

2024-08-08 20:21 UTC, sasanjac requested changes

2024-08-09 11:25 UTC, SebastianDD commented on pyproject.toml
> +    import = ["pandas"]
using the `import_user_data()`, the module 'pandas' is necessary.
But for using feather (no matter if export or import), the module 'pandas' and 'pyarrow' is necessary.
Will be renamed to io-arrow and io-basic.

2024-08-12 14:35 UTC, sasanjac approved these changes

2024-08-12 14:35 UTC, merged