BREAKING CHANGE: upgrade to PowerFactory 2024
ieeh-tu-dresden/powerfactory-tools pull request #263
Opened 2024-08-26 12:45 UTC by SebastianDD

Fixes #150

2024-08-27 13:45 UTC, SebastianDD commented
consider to build python-version-specific wheels or to add in readme `uv sync --python 3.12` as example code to specify the python version to be used

2024-08-30 08:08 UTC, sasanjac requested changes

2024-08-30 10:57 UTC, SebastianDD commented on src/powerfactory_tools/utils/io.py
>      ) -> pathlib.Path:
done

2024-08-30 10:57 UTC, SebastianDD commented on src/powerfactory_tools/__version__.py
> +# :copyright: Copyright (c) Institute of Electrical Power Systems and High Voltage Engineering - TU Dresden, 2022-2024.
Fixes #267

2024-08-30 11:59 UTC, sasanjac requested changes

2024-08-30 11:59 UTC, sasanjac commented on src/powerfactory_tools/utils/io.py
> +        msg = "This method should be overridden in a subclass"
```suggestion
        msg = "This method should be implemented in a subclass"
```

2024-08-30 11:59 UTC, sasanjac commented on src/powerfactory_tools/utils/io.py
> +class BaseExportHandler(abc.ABC):
```suggestion
class ExportHandler(abc.ABC):
```

2024-08-30 11:59 UTC, sasanjac commented on src/powerfactory_tools/versions/pf2022/utils/io.py
> +from powerfactory_tools.utils.io import BaseExportHandler
```suggestion
from powerfactory_tools.utils.io import ExportHandler as BaseExportHandler
```

2024-08-30 11:59 UTC, sasanjac commented on src/powerfactory_tools/versions/pf2024/utils/io.py
> +from powerfactory_tools.utils.io import BaseExportHandler
```suggestion
from powerfactory_tools.utils.io import ExportHandler as BaseExportHandler
```

2024-08-30 12:19 UTC, sasanjac approved these changes

2024-08-30 12:20 UTC, merged